class Categoria < ApplicationRecord
	#belongs_to :media
	#Momentaneamente las pondre aquí ya luego las paso  a la base con el crud listo
  CategoriasMN = [{pequeños_gigantes: "La naturaleza en detalle (Fotografía Macro). Imágenes que resalten la belleza de los detalles diminutos de la naturaleza: Texturas, colores, formas y patrones (insectos, flores, líquenes, semillas, gotas de agua, entre otros) pueden ser tu fuente de inspiración.",
                  fauna: "Latidos de la vida silvestre (Fauna). Animales nativos de México en vida silvestre, desde ambientes marinos hasta las altas montañas. No se aceptan animales en cautiverio, domésticos y/o mascotas.",
              plantas_y_hongos: "El mundo secreto de plantas y hongos. Incluye toda clase de especies vegetales y hongos nativos de México en vida silvestre. No se aceptarán fotografías de plantas u hongos cultivados, de maceta o jardín."},
                  {naturaleza_y_ser_humano: "Ecosistemas y su gente. Imágenes aéreas o terrestres de ecosistemas que destaquen su belleza paisajística o los cambios e impactos que experimentan. También se aceptan fotografías que muestren la interacción entre las personas y la naturaleza, incluyendo los usos tradicionales, expresiones culturales, prácticas sustentables, impactos al entorno y formas de vida vinculadas con la biodiversidad.
  *En el caso de que fotos que tengan imágenes en donde se pueda distinguir a la persona o personas, se deberá contar con la autorización de uso de imagen y en caso de menores de edad deberá contar con la autorización por escrito de los padres o tutores.",
          paisajes_con_ecosistemas: "Incluye cualquier fotografía tomada con equipos moviles (celulares) relacionada con la riqueza natural de México, es decir, animales o plantas en su ambiente natural, paisajes naturales, actividades relacionadas con el hombre y la naturaleza. No se aceptarán fotografías de plantas cultivadas, animales en cautiverio o cualquier otro ambiente controlado."},
          {tema_libre: "(Jóvenes) Cualquier fotografía relacionada con la riqueza natural de México, en condiciones silvestres: es decir, animales o plantas en su ambiente natural, paisajes naturales, actividades relacionadas con el hombre y la naturaleza, impactos y expresiones bioculturales. No se aceptarán fotografías de plantas cultivadas, animales en cautiverio o cualquier otro ambiente controlado.
  En el caso de que la(s) foto(s) tenga(n) imágenes en donde se pueda distinguir a la persona o personas, se deberá contar con la autorización de uso de imagen y en caso de menores de edad deberá contar con la autorización por escrito de los padres o tutores.",
  CoSMoS: "CoSMoS. Montañas y Sierras del centro de México. Fotografías de biodiversidad (animales, plantas, hongos y paisajes representativa del lugar), paisajes, actividades productivas sostenibles, cultura local y problemáticas ambientales que enfrentan las comunidades cercanas a Áreas Naturales Protegidas del centro del país",
  naturaleza_al_alcance_de_tu_mano: "La naturaleza al alcance de tu mano. Con el objetivo de fomentar la creatividad y accesibilidad en la fotografía, el concurso incluye la Categoría Especial: Fotografía con dispositivo móvil (celular, tableta electrónica u otro dispositivo), que refleje la riqueza natural de México, particularmente en las cercanías de las ANPs del proyecto CoSMoS arriba mencionadas. Las imágenes pueden incluir: animales, plantas, hongos en su entorno natural, paisajes y escenas que muestren la relación entre el ser humano y la naturaleza. No se aceptarán fotografías de organismos en cautiverio ni ambientes controlados, fotografías de plantas cultivadas, animales en cautiverio o cualquier otro ambiente controlado."}].freeze
end
  